# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simulationmsg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='simulationmsg.proto',
  package='geoscenario',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13simulationmsg.proto\x12\x0bgeoscenario\"9\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03lat\x18\x02 \x01(\x02\x12\x0b\n\x03lon\x18\x03 \x01(\x02\x12\x0b\n\x03\x61lt\x18\x04 \x01(\x02\"\"\n\x03Way\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07nodeids\x18\x02 \x03(\x05\"\x18\n\x08Scenario\x12\x0c\n\x04name\x18\x01 \x01(\t\"J\n\x0eScenarioResult\x12\x13\n\x0bsubscenario\x18\x01 \x01(\x08\x12\x0e\n\x06minttc\x18\x02 \x01(\x02\x12\x13\n\x0bmindistance\x18\x03 \x01(\x02\"!\n\x0fSubScenarioGoal\x12\x0e\n\x06nodeid\x18\x01 \x01(\x05\"_\n\nPedestrian\x12\x0e\n\x06nodeid\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08velocity\x18\x03 \x01(\x02\x12\x13\n\x0borientation\x18\x04 \x01(\x02\x12\x0c\n\x04path\x18\x05 \x01(\x02\x62\x06proto3')
)




_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='geoscenario.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='geoscenario.Node.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lat', full_name='geoscenario.Node.lat', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lon', full_name='geoscenario.Node.lon', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alt', full_name='geoscenario.Node.alt', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=93,
)


_WAY = _descriptor.Descriptor(
  name='Way',
  full_name='geoscenario.Way',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='geoscenario.Way.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nodeids', full_name='geoscenario.Way.nodeids', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=129,
)


_SCENARIO = _descriptor.Descriptor(
  name='Scenario',
  full_name='geoscenario.Scenario',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='geoscenario.Scenario.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=155,
)


_SCENARIORESULT = _descriptor.Descriptor(
  name='ScenarioResult',
  full_name='geoscenario.ScenarioResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subscenario', full_name='geoscenario.ScenarioResult.subscenario', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minttc', full_name='geoscenario.ScenarioResult.minttc', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mindistance', full_name='geoscenario.ScenarioResult.mindistance', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=231,
)


_SUBSCENARIOGOAL = _descriptor.Descriptor(
  name='SubScenarioGoal',
  full_name='geoscenario.SubScenarioGoal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodeid', full_name='geoscenario.SubScenarioGoal.nodeid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=266,
)


_PEDESTRIAN = _descriptor.Descriptor(
  name='Pedestrian',
  full_name='geoscenario.Pedestrian',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodeid', full_name='geoscenario.Pedestrian.nodeid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='geoscenario.Pedestrian.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='geoscenario.Pedestrian.velocity', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='geoscenario.Pedestrian.orientation', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='geoscenario.Pedestrian.path', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=363,
)

DESCRIPTOR.message_types_by_name['Node'] = _NODE
DESCRIPTOR.message_types_by_name['Way'] = _WAY
DESCRIPTOR.message_types_by_name['Scenario'] = _SCENARIO
DESCRIPTOR.message_types_by_name['ScenarioResult'] = _SCENARIORESULT
DESCRIPTOR.message_types_by_name['SubScenarioGoal'] = _SUBSCENARIOGOAL
DESCRIPTOR.message_types_by_name['Pedestrian'] = _PEDESTRIAN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), {
  'DESCRIPTOR' : _NODE,
  '__module__' : 'simulationmsg_pb2'
  # @@protoc_insertion_point(class_scope:geoscenario.Node)
  })
_sym_db.RegisterMessage(Node)

Way = _reflection.GeneratedProtocolMessageType('Way', (_message.Message,), {
  'DESCRIPTOR' : _WAY,
  '__module__' : 'simulationmsg_pb2'
  # @@protoc_insertion_point(class_scope:geoscenario.Way)
  })
_sym_db.RegisterMessage(Way)

Scenario = _reflection.GeneratedProtocolMessageType('Scenario', (_message.Message,), {
  'DESCRIPTOR' : _SCENARIO,
  '__module__' : 'simulationmsg_pb2'
  # @@protoc_insertion_point(class_scope:geoscenario.Scenario)
  })
_sym_db.RegisterMessage(Scenario)

ScenarioResult = _reflection.GeneratedProtocolMessageType('ScenarioResult', (_message.Message,), {
  'DESCRIPTOR' : _SCENARIORESULT,
  '__module__' : 'simulationmsg_pb2'
  # @@protoc_insertion_point(class_scope:geoscenario.ScenarioResult)
  })
_sym_db.RegisterMessage(ScenarioResult)

SubScenarioGoal = _reflection.GeneratedProtocolMessageType('SubScenarioGoal', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCENARIOGOAL,
  '__module__' : 'simulationmsg_pb2'
  # @@protoc_insertion_point(class_scope:geoscenario.SubScenarioGoal)
  })
_sym_db.RegisterMessage(SubScenarioGoal)

Pedestrian = _reflection.GeneratedProtocolMessageType('Pedestrian', (_message.Message,), {
  'DESCRIPTOR' : _PEDESTRIAN,
  '__module__' : 'simulationmsg_pb2'
  # @@protoc_insertion_point(class_scope:geoscenario.Pedestrian)
  })
_sym_db.RegisterMessage(Pedestrian)


# @@protoc_insertion_point(module_scope)
